language: cpp

env:
  global:
    - LINUX_DIST=trusty

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: true
      compiler: gcc

    # - os: osx
    #   compiler: gcc

before_install:
  # Install dependencies
    - |
      if [[ ${TRAVIS_OS_NAME} == "linux" ]]; then
        sudo add-apt-repository -y ppa:teivg/graph
        sudo add-apt-repository -y ppa:george-edison55/cmake-3.x
        sudo apt-get update
        sudo ldconfig
      elif [[ ${TRAVIS_OS_NAME} == "osx" ]]; then
        brew update
        brew outdated cmake || brew upgrade cmake
      fi

install:
    - echo ${PATH}
    - echo ${CXX}
    - ${CXX} --version

    - |
      if [[ ${TRAVIS_OS_NAME} == "linux" ]]; then
        sudo apt-get install -qq -y cmake3 libvips-dev libavcodec-dev libswscale-dev
        sudo ldconfig
      elif [[ ${TRAVIS_OS_NAME} == "osx" ]]; then
        brew install libav || brew upgrade libav
        brew install vips || brew upgrade vips
      fi

script:
    ############################################################################
    # Build main and tests
    ############################################################################
     - mkdir -p build
     - cd build
     - cmake .. 
     - make
     - ./tifig -v ../fixtures/1.heic test.jpg
     - ./tifig -v -p ../fixtures/1.heic parallel.jpg
     - ./tifig -v -t ../fixtures/1.heic thumb.jpg
