language: cpp
sudo: required
os : linux
dist: trusty

before_install:
  - CC=gcc-5 && CXX=g++-5
  - sudo add-apt-repository -y ppa:teivg/graph
  - sudo add-apt-repository -y ppa:jonathonf/ffmpeg-3
  - sudo add-apt-repository -y ppa:george-edison55/cmake-3.x
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update

install:
  - sudo apt-get install -qq -y g++-5 cmake3 libvips-dev libavcodec-dev libswscale-dev
  - sudo ldconfig

script:
    ############################################################################
    # Build main and tests
    ############################################################################
     - mkdir -p build
     - cd build
     - cmake .. 
     - make
     - ./tifig -v ../fixtures/1.heic test.jpg
     - ./tifig -v -t ../fixtures/1.heic thumb.jpg
